### ISSUE TITLE
Fix broken chain spec links on github page

### ISSUE THREAD

**Issue by wischli** [substrate-developer-hub/cumulus-workshop#16]
The deployed github page does not resolve the [relative path to the example chain specs](https://substrate.dev/cumulus-workshop/#/1-prep/2-chain-spec) for rococo correctly in section 1.2 chain-spec: 

```
https://substrate.dev/cumulus-workshop/#/../specs/rococo-local.json
```

Obviously, it should be:
```
https://substrate.dev/cumulus-workshop/specs/rococo-local.json
```

Moreover, this is not caught by the current CI `link-check`.

**Comment by JoshOrndorff** [comment]
Fixed in 9b86a29

This seems like a docsify issue which will go away if/when this workshop is integrated with the main Substrate devhub.
