### ISSUE TITLE
Parachain failed to produce blocks

### ISSUE THREAD

**Issue by ianhe8x** [substrate-developer-hub/cumulus-workshop#29]
I followed the steps and just finished the step to register my para-chain in the relay chain.
Now I can see the console output of parachain node start printing things like `[Parachain] Imported #1 (0xc643…4974)`
but it stucked at `#1` and never make it to `#2`. Do you have any idea why it behaviors like this?

**Comment by JoshOrndorff** [comment]
Imported #1 is a good sign, but getting stuck is not. We'll need more details to help you diagnose this. Do you have complete logs of the nodes? Any errors in any of the node logs? Steps to reproduce?
