### ISSUE TITLE
Websocket port not accessible from docker

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/cumulus-workshop#3]
This repo attempts to include a docker image for learners to follow along without needing to install the entire rust toolchain and build both polkadot and cumulus. The `Dockerfile` is in the root of the repo and is relatively straightforward.

I've been building and running the image with these commands run in the root of this repository:
```bash
# Build the image
sudo docker build .

# Run the image
sudo docker run --publish 9944:9944 -it 566c49abe980
```

I though specifying `EXPOSE 9944` in the `Dockerfile` and including `--publish 9944:9944` would make my websocket port accessible so I could use Apps UI, but Apps will not connect. It just gives the errors:
```
WebSocket connection to 'ws://127.0.0.1:9944/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
connect @ polkadotjs.cb2670d3.js:1
polkadotjs.cb2670d3.js:1 2020-06-23 09:45:08          API-WS: disconnected from ws://127.0.0.1:9944/ code: '1006' reason: ''
```

But it seems the docker image is _somehow_ using port 9944. Because when I run the image with the command above and then run another polkadot node on my actual local OS (not in the container) the node tells me `Unable to bind RPC server to 127.0.0.1:9944. Trying random port.` This makes me think that the docker image is actually binding the port as I expected, but for some reason Aps still can't connect.

**Comment by JoshOrndorff** [comment]
In #4 @wheresaddie wrote:

> docker images from parity:
> https://hub.docker.com/r/parity/polkadot/tags
>
> One more docker example that works with Apps UI:
> https://github.com/usetech-llc/nft_parachain/blob/master/docker-compose.yml

It seems I have the same issue with the published polkadot image. I can't get a UI to connect to it.

**Comment by wheresaddie** [comment]
> In #4 @wheresaddie wrote:
> 
> > docker images from parity:
> > https://hub.docker.com/r/parity/polkadot/tags
> > One more docker example that works with Apps UI:
> > https://github.com/usetech-llc/nft_parachain/blob/master/docker-compose.yml
> 
> It seems I have the same issue with the published polkadot image. I can't get a UI to connect to it.

hmm strange-- let me look into this .. I wasn't having the issue when I tried it a few weeks ago

**Comment by JoshOrndorff** [comment]
@ Lovlaced taught me that because the node is running inside the container, I have to use `--network=host` with docker, or pass `--ws-external` to the node. So that part of the mystery is solved. She also recommended that I should have two different docker containers. One for the polkadot node and one for the parachain node.

**Comment by wheresaddie** [comment]
this is a great tip- thanks for the clarification and update @JoshOrndorff

**Comment by ksaikiranr** [comment]
Hi All,
From my understanding, the entrypoint of Dockerfile is bash shell and we are not invoking any server throughout Dockerfile.
Docker run is able to create internal to external port binding since $ netstat -nltp show on host. So we need to run the server using RUN or ENTRYPOINT so that servers inside the container start 9944 port. I could not find which binary will start the server.

**Comment by wheresaddie** [comment]
is it possible only binds to ipv6 localhost ([::1]) and not ipv4 localhost (127.0.0.1)?
Some applications default to ipv6 resolve first, and other apps, like node.js default to ipv4 lookup. ... @JoshOrndorff

**Comment by JoshOrndorff** [comment]
These networking issues have been addressed by this section npx prettier --print-width 120 --prose-wrap=always --write **/*.md
