### ISSUE TITLE
Update for Parachains V1

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/cumulus-workshop#33]
Cumulus now supports Parachains V1, and Rococo V1 will launch soon.

The Moonbeam team has already done this update and took some notes that may be helpful for whoever updates this tutorial. You may use this content freely <3

https://github.com/PureStake/moonbeam/blob/4e62adf2e487dbe3f374f8504919180de1929ba3/launch-notes.md

**Comment by jimmychu0807** [comment]
thank you @JoshOrndorff

**Comment by riusricardo** [comment]
:rocket:
