### ISSUE TITLE
With updated chainspec, polkadot-js runs with error Error: 1002: Verification Error: Runtime error: Execution failed: ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress")

### ISSUE THREAD

**Issue by h4n0** [substrate-developer-hub/cumulus-workshop#42]
Hi, 

I tried the updated rococo-local.json from the commit [Update ChainSpecs](https://github.com/substrate-developer-hub/cumulus-workshop/commit/e22266a7ddde2a7638c7c6c4742807b5872af6cb) chain spec and it worked with relay chain but not with my client using polkadot-js api. 

Every time I call a sudo method to interact with relay chain, this error comes 
>Error: 1002: Verification Error: Runtime error: Execution failed: ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress")

However, it worked with the previous chain spec version before this commit. 

I tried to diff them but unfortunately it's nothing readable but raw data only.

Could you tell me what is the change between these two and why it's updated?

**Comment by riusricardo** [comment]
Please check if this solution works for you:
https://stackoverflow.com/questions/66114949/could-not-convert-parameter-tx-between-node-and-runtime-no-such-variant-in-en
