### ISSUE TITLE
Building the test parachain collator failed

### ISSUE THREAD

**Issue by tolak** [substrate-developer-hub/cumulus-workshop#5]
I follow the README file to build the test parachain collator, after checkout to commit 05a83e8 under cumlus repo root,
i got following errors:
error: failed to get `polkadot-primitives` as a dependency of package `cumulus-consensus v0.1.0 (<my workspace>/cumulus/consensus)`

Caused by:
  failed to load source for dependency `polkadot-primitives`

Caused by:
  Unable to update https://github.com/paritytech/polkadot?branch=cumulus-branch#91f3e68f

Caused by:
  revspec '91f3e68f5750dff7bddedeb846ff55447e8cf8f8' not found; class=Reference (4); code=NotFound (-3)

**Comment by tolak** [comment]
I try to change Cargo.lock file to use latest commit of branch cumulus-branch, can not compile either.

**Comment by JoshOrndorff** [comment]
Hi @tolak Thanks for trying out the workshop. I'm happy to help.

Although this code is over a month old, I was still able to compile from scratch yesterday. So we have t ofigure out what's different between your system and mine. Can you please post the output of these commands run from the cumulus repo directory?

* `git status`
* `rustup show`

**Comment by tolak** [comment]
Hi @JoshOrndorff  Thanks for your help. The entire output message is below:

➜  cumulus git:(05a83e8) git status
HEAD detached at 05a83e8
nothing to commit, working tree clean
➜  cumulus git:(05a83e8) rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/wwf/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.45.1 (c367798cf 2020-07-26)

➜  cumulus git:(05a83e8) cargo check -p cumulus-test-parachain-collator

    Updating git repository `https://github.com/paritytech/polkadot`
error: failed to get `polkadot-primitives` as a dependency of package `cumulus-consensus v0.1.0 (/Users/wwf/workspace/PhalaProjects/cumulus/consensus)`

Caused by:
  failed to load source for dependency `polkadot-primitives`

Caused by:
  Unable to update https://github.com/paritytech/polkadot?branch=cumulus-branch#91f3e68f

Caused by:
  revspec '91f3e68f5750dff7bddedeb846ff55447e8cf8f8' not found; class=Reference (4); code=NotFound (-3)


It seems that polkadot repo miss commit "91f3e68f5750dff7bddedeb846ff55447e8cf8f8", i do find nothing about this commit within polkadot repo.

**Comment by JoshOrndorff** [comment]
Hmm, this is quite strange. I agree that the error is saying it can't find that commit, but the commit exists. Can you open this link successfully? https://github.com/paritytech/polkadot/tree/91f3e68f5750dff7bddedeb846ff55447e8cf8f8

**Comment by tolak** [comment]
I can open this link. But it's strange that i can't chekout to this commit under my polkadot repo root.

➜  polkadot git:(master) git checkout 91f3e68f5750dff7bddedeb846ff55447e8cf8f8
fatal: reference is not a tree: 91f3e68f5750dff7bddedeb846ff55447e8cf8f8

**Comment by tolak** [comment]
I got help from polkadot riot chat that someone tell me i should first run "git fetch origin 91f3e68f5750dff7bddedeb846ff55447e8cf8f8" to fetch this commit because this commit does not belong to any branch now maybe the branch was already deleted. I did it and it really can checkout to this commmit in my local repo now.

But if i compile cumulus, the polkadot is needed by other module, i can not do fetch job by my self because all are done by script. Is there any way to solve this?

**Comment by JoshOrndorff** [comment]
You've found the problem. It's because that branch was deleted. I'll update this workshop in the next few weeks.

For now the best you can do is try with a newer cumulus. The latest master branch is really cool, and there is a public testnet just launched yesterday that uses it. The concepts are the same, but some things have changed. In particular any references to `cumulus-test-parachain-collator` are now `rococo-collator`.

If you do try it out on a newer cumulus, PRs to this workshop are quite welcome.

**Comment by tolak** [comment]
Yeah this is what i am trying to do next. Thanks for your help and i would send a PR if there is a better way can work this out.

**Comment by JoshOrndorff** [comment]
I just updated the workshop. I hope you'll try it out and let me know your experience. Issues and PRs are very welcome.

**Comment by tolak** [comment]
Thank you Josh, I watched the seminar last night(Beijing). I just followed the new workshop document to deploy the relay chain and parachain locally, everything is OK including transfering between relay chain and parachain. You did a awesome job man! Thanks again!
