### ISSUE TITLE
feature `resolver` is required

### ISSUE THREAD

**Issue by tansaku** [substrate-developer-hub/cumulus-workshop#94]
Following on from https://github.com/substrate-developer-hub/cumulus-workshop/issues/54#issuecomment-851689063 I'm having another go at the workshop.

I'm currently at https://substrate.dev/cumulus-workshop/#/en/1-prep/1-compiling and 

```
# Switch into the Polkadot directory
cd polkadot

# Checkout the proper commit
git checkout v0.9.8

# Build the relay chain Node
cargo build --release
```

I'm getting this error:

```
HEAD is now at 3a10ee63c Staking Miner (#3141)
❯ cargo build --release
    Updating git repository `https://github.com/paritytech/substrate`
    Updating crates.io index
    Updating git repository `https://github.com/paritytech/grandpa-bridge-gadget`
  Downloaded static_init v0.5.2
  Downloaded target-lexicon v0.12.0
  Downloaded socket2 v0.4.0
  Downloaded trie-db v0.22.5
  Downloaded security-framework v2.2.0
  Downloaded serde v1.0.126
  Downloaded arrayvec v0.7.0
  Downloaded tracing-core v0.1.18
  Downloaded parity-db v0.2.4
  Downloaded wasmi-validation v0.4.0
  Downloaded futures v0.3.15
  Downloaded async-executor v1.4.1
  Downloaded libp2p-core v0.28.2
error: failed to parse manifest at `/Users/samueljoseph/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.28.2/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature

```

this is my cargo version:

```
❯ cargo --version
cargo 1.49.0 (d00d64df9 2020-12-05)
```

I'm on OSX 11.5.1 (20G80)

I can't see a specification of which version of cargo we should be using for the workshop - is that something to add maybe?

**Comment by tansaku** [comment]
I just upgraded 

```
❯ cargo --version
cargo 1.54.0 (5ae8d74b3 2021-06-22)
```

and it all worked.  Is there some way to require a minimum version of cargo?  Or perhaps just mention one in the workshop?

**Comment by NukeManDan** [comment]
It is generally assumed that people are building with the latest toolchain, unless explicitly needing to use an older nightly for some reason. (There have been times thus was needed historically)

A PR to remind of this and how to update would be great, sure!

**Comment by tansaku** [comment]
here you go https://github.com/substrate-developer-hub/cumulus-workshop/pull/95 :-)
